### ISSUE TITLE
Incorrect non-edge count in TESTsbm.R

### ISSUE THREAD

**Issue by njosephs** [danieledurante/TESTsbm#1]
In TESTsbm.R, the function log_pY_z incorrectly counts the number of non-edges between clusters. This is because line 221 melts `1 - Y` which has 1s down the diagonal. This results in non-integer counts for `lowerTriangle(No_Edge,diag=TRUE)`.

This can be fixed as follows:

> `Y_c <- 1 - Y`
> `diag(Y_c) <- 0`
> `non_edge_counts <- melt(Y_c)`

**Comment by danieledurante** [comment]
Thank you! The bug in the function `log_pY_z()` has been corrected and the whole repository has been updated accordingly.

**Comment by danieledurante** [comment]
Thank you! The bug in the function `log_pY_z()` has been corrected and the whole repository has been updated accordingly.
